{% set VERSION = '3.5.2b2.post19' %}
{% set REPO = 'https://github.com/sci-bots/platformio-core' %}
{% set COMMIT = '58ebd7ea2a3697a84eee33f6dc9e5e74734d4d1b' %}
package:
  name: platformio
  version: {{ VERSION }}

source:
  url: {{ REPO }}/archive/{{ COMMIT }}.tar.gz

build:
  number: 4
  entry_points:
    - pio = platformio.__main__:main
    - platformio = platformio.__main__:main
  noarch: true
  string: 'g{{ COMMIT[:8] }}_2'

requirements:
  build:
    - bottle <0.13
    - click <6,>=5
    - colorama
    - lockfile <0.13,>=0.9.1
    - pip
    - pyserial >=3,<4
    - python
    - requests <3,>=2.4.0
    - semantic_version >=2.5.0
    - six

  run:
    - bottle <0.13
    - click <6,>=5
    - colorama
    - lockfile <0.13,>=0.9.1
    - platformio-helpers >=0.8
    - pyserial >=3,<4
    - python
    - requests <3,>=2.4.0
    - semantic_version >=2.5.0
    - six

about:
  home: {{ REPO }}
  license: Apache 2.0
