{% set VERSION = '3.5.2b2.post16' %}
{% set REPO = 'https://github.com/sci-bots/platformio-core' %}
{% set COMMIT = '7bd34d6226ae82d9ead173d34230a8449f992b62' %}
package:
  name: platformio
  version: {{ VERSION }}

source:
  url: {{ REPO }}/archive/{{ COMMIT }}.tar.gz

build:
  number: 0
  entry_points:
    - pio = platformio.__main__:main
    - platformio = platformio.__main__:main
  noarch: true
  string: 'g{{ COMMIT[:8] }}'

requirements:
  build:
    - bottle <0.13
    - click <6,>=5
    - colorama
    - lockfile <0.13,>=0.9.1
    - pip
    - pyserial >=3,<4
    - python
    - requests <3,>=2.4.0
    - semantic_version >=2.5.0

  run:
    - bottle <0.13
    - click <6,>=5
    - colorama
    - lockfile <0.13,>=0.9.1
    - pyserial >=3,<4
    - python
    - requests <3,>=2.4.0
    - semantic_version >=2.5.0

about:
  home: {{ REPO }}
  license: Apache 2.0
