{% set VERSION = '3.5.0' %}
{% set REPO = 'https://github.com/platformio/platformio-core' %}
package:
  name: platformio
  version: {{ VERSION }}

source:
  url: {{ REPO }}/archive/v{{ VERSION }}.tar.gz

build:
  number: 0
  entry_points:
    - pio = platformio.__main__:main
    - platformio = platformio.__main__:main

requirements:
  build:
    - bottle <0.13
    - click <6,>=5
    - colorama
    - lockfile <0.13,>=0.9.1
    - pip
    - pyserial >=3,<4
    - python
    - requests <3,>=2.4.0
    - semantic_version >=2.5.0

  run:
    - bottle <0.13
    - click <6,>=5
    - colorama
    - lockfile <0.13,>=0.9.1
    - pyserial >=3,<4
    - python
    - requests <3,>=2.4.0
    - semantic_version >=2.5.0

about:
  home: {{ REPO }}
  license: Apache 2.0
