{% set VERSION = '3.5.2b2.post20' %}
{% set REPO = 'https://github.com/sci-bots/platformio-core' %}
{% set COMMIT = '42c1c8049ccee75001abff5aae2077da3672c77f' %}
{% set BUILD_NUMBER = 0 %}
package:
  name: platformio
  version: {{ VERSION }}

source:
  url: {{ REPO }}/archive/{{ COMMIT }}.tar.gz

build:
  number: {{ BUILD_NUMBER }}
  entry_points:
    - pio = platformio.__main__:main
    - platformio = platformio.__main__:main
  noarch: true
  string: 'g{{ COMMIT[:8] }}_{{ BUILD_NUMBER }}'

requirements:
  build:
    - bottle <0.13
    - click <6,>=5
    - colorama
    - lockfile <0.13,>=0.9.1
    - pip
    - pyserial >=3,<4
    - python
    - requests <3,>=2.4.0
    - semantic_version >=2.5.0
    - six

  run:
    - bottle <0.13
    - click <6,>=5
    - colorama
    - lockfile <0.13,>=0.9.1
    - platformio-helpers >=0.8
    - pyserial >=3,<4
    - python
    - requests <3,>=2.4.0
    - semantic_version >=2.5.0
    - six

about:
  home: {{ REPO }}
  license: Apache 2.0
